### ISSUE TITLE
XML care nu se transforma in format PDF

### ISSUE THREAD

**Issue by vicosx12** [gabizz/e-factura-xml2print#1]
https://drive.google.com/file/d/1ScOEzutWX3muVtmCZpvxNOYeW4K3FDPO/view?usp=sharing

Xml din link-ul de mai sus, nu stie sa-l parseze.

"Application error: a client-side exception has occurred (see the browser console for more information)."

{"detail":"Not Found"}

**Comment by gabizz** [comment]
rezolvat ieri, vezi comment-ul de la noutati din app pentru IBCV Iasi. multumesc pentru semnalare, am fost cam ocupat, nu am intrat pe git :)
