### ISSUE TITLE
Serviciu web API

### ISSUE THREAD

**Issue by vicosx12** [gabizz/e-factura-xml2print#2]
Se poate converti si ca un serviciu web API, in care sa transmitem ca parametru fisierul xml si sa primim ca raspuns ceea ce genereaza butonul "Salveaza PDF"?

Multumesc.

**Comment by gabizz** [comment]
teoretic este posibil, nu intră în scopul acestui proiect, dar .... vezi in documentatia de la next.js "api routes".  asta e partea simplă.  export const route = (req, res)=> ....etc... 

ÎNSĂ:

**Problema 1:**  Eu, in acest proiect generez pdf-ul "quick-n-dirty", cu jsPdf, dintr-un snapshot al canvas-ului html5 facut cu html2canvas. Merge foarte bine in browser. Server-side, nu cred ca merge, din câte știu eu, html2canvas necesită un DOM propriu-zis, nu unul virtual. Așadar, ar trebui să folosești o altă soluție, de ex. js2pdf (cu sintaxa aferentă) pentru a genera pdf-ul server-side și apoi să-l trimiți ca răspuns sub forma de stream. 

**Problema 2:** Costul. Un alt aspect de care va trebui să ții cont dacă alegi să găzduiești soluția într-un sistem cu deployment automat, de ex. vercel, netlify, aws lambda etc.... api endpoint-ul tău va fi de fapt o  "funcție lambda" și cred că NU vei vrea să o lași publică, pentru a fi executată nesecurizat de oricine, întrucât în toate planurile free ai o limita maximă de apelări (gratuite). Dacă faci o treabă bună și se prinde lumea, crede-mă, 1 milion de request-uri nu e chiar atât de mult. Deci, ar fi intelept sa iti securizezi end-point-ul.

Eu, prin proiectul ăsta, am realizat ce mi-am propus. Ofer (gratuit) oricui posibilitatea de "vedea" ce e în xml, rapid și ușor. Încet, încet, cam toate soluțiile de contabilitate pentru bugetari își implementează propria procedură de import a xml-ului, deci la un moment dat, probabil că proiectul meu nu va mai fi folosit, dar și-a atins scopul și sunt foarte mulțumit că am putut fi de folos. 

Dar dacă vrei neapărat să faci asta, poți oricând să faci un fork sau să te inspiri din codul meu, e perfect ok.

Sper că ți-am răspuns suficient de clar

O zi bună

Gabi M.
